Clear errno after trying multiple service dirs
davmac314/dinit pull request #125
Opened 2022-11-13 14:26 UTC by q66

The previous code would remain errno to be set after trying bad service directories (despite having encountered a valid one later), which would result in nonsensical error messages outside that path.

2022-11-13 14:29 UTC, q66 commented
the particular error is `Error reading dependency directory '/whatever' for <whatever> service` in `process_dep_dir`; this is a warning, not a hard error (so it has no effect on behavior), but it still makes no sense for it to say anything (as if you try e.g. 2 service dirs, the first one sets errno and the second one succeeds, we don't care about why the first one failed)

2022-11-14 03:08 UTC, davmac314 commented
Hmm, I think the better fix location is in `process_dep_dir`. It starts correctly by clearing `errno`:
```
    errno = 0;
    dirent * dent = readdir(depdir);
```
but then in the `while` loop it should be resetting it again just before it does:
```
        dent = readdir(depdir);
```
Fixing it here would be more robust since it would avoid any similar mistakes in the future (generally we shouldn't rely on a non-trivial function call preserving `errno`).

2022-11-14 03:10 UTC, davmac314 requested changes
Please set errno to 0 in `process_dep_dir` instead (before the call to `readdir` in the `while` loop).

2022-11-20 03:03 UTC, merged

2022-11-20 03:03 UTC, davmac314 commented
I'll just make the change myself after merging. Thanks for raising this.

2022-11-20 16:12 UTC, q66 commented
sorry, i didn't get to checking this again - thanks for addressing it