CI: Minor improvements
davmac314/dinit pull request #200
Opened 2023-06-18 17:31 UTC by mobin-2008

Hey.

ToDo:

- [x] Don't run Make based CI for Meson files changes
- [x] Don't run FreeBSD CI for Meson files changes
- [x] Upload `src/igr-tests/*/output/*` files on failure (Github actions only)

Regards

`Signed-off-by: Mobin "Hojjat" Aydinfar <mobin@mobintestserver.ir>`

2023-06-18 17:34 UTC, mobin-2008 commented
Looks strange, but Github actions doesn't triggered at all! Needs work (testing CI related things in fork repo is painful).

2023-06-21 10:41 UTC, davmac314 requested changes

2023-06-21 10:46 UTC, mobin-2008 commented on .github/workflows/regular_ci.yml
> +    - name: Getting depends & build & unit tests & integration tests
Seems like if steps include ` - uses` with `name`, cannot have another step (GitHub syntax checker gave me some weird error about it).

2023-06-21 10:48 UTC, mobin-2008 commented on .github/workflows/meson_ci.yml
> +      - '!doc/SECURITY'
I will test it.

2023-06-21 10:49 UTC, davmac314 commented on .github/workflows/regular_ci.yml
> +    - name: Getting depends & build & unit tests & integration tests
If that was a pre-existing problem, it should be fixed in an individual commit, not squashed in with another change

2023-06-21 12:05 UTC, mobin-2008 commented on .github/workflows/regular_ci.yml
> +    - name: Getting depends & build & unit tests & integration tests
Seems like not needed

2023-06-21 21:12 UTC, davmac314 approved these changes
Looks much better, thanks

2023-06-21 22:11 UTC, merged