CI: New ci which focus on security hardening
davmac314/dinit pull request #216
Opened 2023-08-14 11:24 UTC by mobin-2008

`Signed-off-by: Mobin "Hojjat" Aydinfar <mobin@mobintestserver.ir>`

Also it tests configure script which is good I think.

Regards

2023-08-14 12:17 UTC, mobin-2008 commented
Seems like it needs more investigation. I'll figure it out.

2023-08-14 12:40 UTC, davmac314 commented
Also, please don't add yet another CI, just modify an existing one. FreeBSD would be a good choice since it's already using clang.

2023-08-17 12:39 UTC, davmac314 requested changes
When I said don't add another CI, I meant don't add another task.  There are too many already IMO. We don't need three different tasks for FreeBSD, one is enough.

2023-08-17 13:38 UTC, davmac314 approved these changes

2023-08-17 13:39 UTC, merged