meson: Use shell globbing for listing igr-tests
davmac314/dinit pull request #272
Opened 2024-01-07 12:04 UTC by mobin-2008

There was at least 2 new tests which doesn't run in meson builds, This PR use shell globbing for listing igr-tests which is automated.

`Signed-off-by: Mobin "Hojjat" Aydinfar <mobin@mobintestserver.ir>`

2024-01-07 23:54 UTC, davmac314 requested changes
This modification involves invoking two separate shell commands and is clearly fighting against meson's limitations as well as using a brittle hack to identify tests. As we're approaching 1.0 release I think it's not the time to introduce any hacks in the build.

As I've suggested before, the right way to run the integration tests is via `igr-runner` itself. If you really want to run the tests individually from the meson build then the best solution is probably to make changes to `igr-runner` necessary to allow it to list available tests and to run an individual test, and then have the meson build use that functionality.

The change to use `igr-runner` needs to happen at some point. The integration tests will be re-engineered soon. I warned about this a while back, most recently in August, see https://github.com/davmac314/dinit/pull/212.

> I would still prefer to run tests via igr-runner. As we get closer to 1.0 I plan to re-work the integration tests significantly and updating the meson build is going to be difficult to sustain.

If you don't want to do that now, then stick to listing the individual tests, not a hack which lists directories via a shell command greps in the source of igr-runner to try to identify tests. But it will most likely be necessary to switch to igr-runner at some point regardless.

2024-01-08 15:31 UTC, mobin-2008 commented
So I'm going to change this PR to add these new tests. I will open a issue to discuss about re-engineering `igr-runner` (and probably working on it after #263 got merged).

2024-01-10 22:57 UTC, davmac314 commented
I would like to do a release this weekend. Will you be able to update this PR by then? I can do it myself if you prefer

2024-01-10 23:12 UTC, mobin-2008 commented
> I would like to do a release this weekend. Will you be able to update this PR by then (by Monday)? I can do it myself if you prefer

I'm not sure to have free time, thanks :)

2024-01-12 12:52 UTC, davmac314 commented
I have added the missing integration tests to the meson build in a separate commit

2024-01-12 12:52 UTC, closed without merging