control: Don't call process_packet() when bad_conn_closed is set
davmac314/dinit pull request #354
Opened 2024-07-21 13:50 UTC by mobin-2008

Sending garbage data and then closing the connection could lead into out-of-memory. Because after closing the connection, Dinit will stuck in `(rbuf.get_length() >= chklen)` while loop and then the outbuf buffer is used because the connection fd is not available anymore. This triggers the OOM detector in the fuzzer and can result in segfault when Dinit is used as init of system.

It's harmless because triggering it requires root or particular user (the user who starts dinit) access. See https://github.com/davmac314/dinit/blob/master/doc/SECURITY

Firstly detected in https://github.com/davmac314/dinit/actions/runs/7233843212

`Signed-off-by: Mobin Aydinfar <mobin@mobintestserver.ir>`

2024-07-21 14:01 UTC, mobin-2008 commented
@davmac314 I also started a fuzzer to make sure this problem is resolved: https://github.com/mobin-2008/dinit/actions/runs/10028795810/job/27716167886. I will request review when it succeeded.

I will write and sent the test about this scenario in separate PR.

2024-07-21 22:52 UTC, davmac314 commented
> I will write and sent the test about this scenario in separate PR.

Let's just wait and get the test in the same PR. That's the usual process, and it ensures that the test does not get forgotten.

Thanks for this, the change itself is fine.

2024-07-22 04:38 UTC, mobin-2008 commented
> > I will write and sent the test about this scenario in separate PR.
> 
> Let's just wait and get the test in the same PR. That's the usual process, and it ensures that the test does not get forgotten.

I wasn't sure that I could have enough time for it but I have now. I was thinking about more tests about this issue but I think the more testing is the purpose of fuzzer not cptests (For example passing a valid command following with an invalid command).

Test is ready for review.

2024-07-23 13:29 UTC, davmac314 requested changes

2024-07-23 13:29 UTC, davmac314 commented on src/control.cc
>              if (!process_packet()) {
The check for bad_conn_close should be here (not in the `while` condition).

    if (!process_packet() || bad_conn_close) {

2024-07-23 14:16 UTC, mobin-2008 commented on src/tests/cptests/cptests.cc
> +    event_loop.regd_bidi_watchers[fd]->read_ready(event_loop, fd);
I implemented `set_watches` and `get_watches` in test infrastructure.

2024-07-24 08:22 UTC, davmac314 approved these changes
Looks good, thanks

2024-07-24 08:26 UTC, merged